spring:
  application:
    name:
      file-sharing-eureka-server

  profiles:
    active: ${PROFILE}

  config:
    import: 'configserver:'

  cloud:
    config:
      uri: ${CONFIG_SERVER_URI}

    loadbalancer:
      # Вместо Ribbon будем использовать Spring Cloud Load Balancer
      ribbon:
        enabled: false